version: '3'

networks:
  fuel_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

services:
  scenario1:
    build:
      context: ./scenario1
      dockerfile: Dockerfile
    ports:
      - '10001:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.1

  scenario2:
    build:
      context: ./scenario2
      dockerfile: Dockerfile
    ports:
      - '10002:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.2

  scenario3:
    build:
      context: ./scenario3
      dockerfile: Dockerfile
    ports:
      - '10003:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.3

  scenario4:
    build:
      context: ./scenario4
      dockerfile: Dockerfile
    ports:
      - '10004:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.4

  scenario5:
    build:
      context: ./scenario5
      dockerfile: Dockerfile
    ports:
      - '10005:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.5

  scenario6:
    build:
      context: ./scenario6
      dockerfile: Dockerfile
    ports:
      - '10006:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.6

  scenario7:
    build:
      context: ./scenario7
      dockerfile: Dockerfile
    ports:
      - '10007:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.7

  scenario8:
    build:
      context: ./scenario8
      dockerfile: Dockerfile
    ports:
      - '10008:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.8

  scenario9:
    build:
      context: ./scenario9
      dockerfile: Dockerfile
    ports:
      - '10009:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.9

  scenario10:
    build:
      context: ./scenario10
      dockerfile: Dockerfile
    ports:
      - '10010:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.10

  scenario11:
    build:
      context: ./scenario11
      dockerfile: Dockerfile
    ports:
      - '10011:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.11

  scenario12:
    build:
      context: ./scenario12
      dockerfile: Dockerfile
    ports:
      - '10012:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.12

  scenario13:
    build:
      context: ./scenario13
      dockerfile: Dockerfile
    ports:
      - '10013:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.13

  scenario14:
    build:
      context: ./scenario14
      dockerfile: Dockerfile
    ports:
      - '10014:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.14

  scenario15:
    build:
      context: ./scenario15
      dockerfile: Dockerfile
    ports:
      - '10015:80'
    volumes:
      - ./menu/:/var/www/html/menu/
    networks:
      fuel_network:
        ipv4_address: 172.22.1.15