version: '3'

networks:
  lab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

services:
  level1:
    build:
      context: ./Level1
      dockerfile: Dockerfile
    ports:
      - '10001:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.1
  level2:
    build:
      context: ./Level2
      dockerfile: Dockerfile
    ports:
      - '10002:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.2
  level3:
    build:
      context: ./Level3
      dockerfile: Dockerfile
    ports:
      - '10003:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.3
  level4:
    build:
      context: ./Level4
      dockerfile: Dockerfile
    ports:
      - '10004:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.4
  level5:
    build:
      context: ./Level5
      dockerfile: Dockerfile
    ports:
      - '10005:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.5
  level6:
    build:
      context: ./Level6
      dockerfile: Dockerfile
    ports:
      - '10006:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.6
  level7:
    build:
      context: ./Level7
      dockerfile: Dockerfile
    ports:
      - '10007:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.7
  level8:
    build:
      context: ./Level8
      dockerfile: Dockerfile
    ports:
      - '10008:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.8
  level9:
    build:
      context: ./Level9
      dockerfile: Dockerfile
    ports:
      - '10009:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.9
  level10:
    build:
      context: ./Level10
      dockerfile: Dockerfile
    ports:
      - '10010:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.10
  level11:
    build:
      context: ./Level11
      dockerfile: Dockerfile
    ports:
      - '10011:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.11
  level12:
    build:
      context: ./Level12
      dockerfile: Dockerfile
    ports:
      - '10012:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.12
  level13:
    build:
      context: ./Level13
      dockerfile: Dockerfile
    ports:
      - '10013:80'
    networks:
      lab_network:
        ipv4_address: 172.22.1.13